#GENERAL
spring:
  application.name: boot
  jmx.enabled: false

#DATA SOURCE
  datasource:
    hikari.pool-name: ${spring.application.name}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari.maximum-pool-size: 3
    url: jdbc:postgresql://127.0.0.1:5432/boot
    username: boot
    password: boot

#JPA
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate.dialect: br.com.eits.common.infrastructure.hibernate.dialect.PostgreSQLDialect
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: true
      hibernate.default_schema: public
      org.hibernate.envers.audit_table_suffix: _audited
      org.hibernate.envers.revision_field_name: revision
      org.hibernate.envers.revision_type_field_name: revision_type
      org.hibernate.envers.default_schema: auditing

#STATIC RESOURCES
  resources.static-locations: classpath:/META-INF/resources/
  resources.chain:
    cache: false
    strategy.content.enabled: true
    strategy.content.paths: /**
      
#THYMELEAF
  thymeleaf:
    mode: HTML
    cache: false
    prefix: classpath:/META-INF/resources/
    suffix: .html
    
#MAIL
  mail:
    host: expressodev.prognus.com.br
    port: 25
    username: no-reply
    password: soAsx2gGX6Rbhk
    from: no-reply@prognus.org
    properties:
      mail.smtp.starttls.enable: false
      mail.smtp.starttls.required: false
      mail.smtp.ssl.enable: false
      mail.smtps.debug: true
      mail.smtp.debug: true
      mail.debug: true
      
#LOGGING
logging.level:
  org.hibernate: INFO
  org.directwebremoting: INFO
  org.springframework.web: INFO
  org.springframework.context.support: INFO
  org.springframework.security: INFO

#FLYWAY
flyway:
  enabled: true
  check-location: true
  schemas: public
  locations: classpath:db/migration
  baseline-on-migrate: true
  sql-migration-prefix: v
  
#DWR
dwr:
  debug: true
  script-compressed: false

#WEB CONTAINER
server:
  context-path:
  compression.enabled: true
  session.persistent: true
  
#SECURITY
security:
  ignored:
  - /**